version: 2
jobs:
  build:
    working_directory: ~/dylan
    docker:
      - image: erlang:20.0.1
    environment:
      MIX_ENV: test
      BASH_ENV: ~/.bashrc
    steps:
      - run: apt-get update
      - run: apt-get install git unzip --yes
      - run: git clone git://github.com/mururu/exenv.git ~/.exenv
      - run: git clone git://github.com/mururu/elixir-build.git ~/.exenv/plugins/elixir-build
      - run: echo 'export PATH="~/.exenv/bin:$PATH"' >> ~/.bashrc
      - run: echo 'eval "$(exenv init -)"' >> ~/.bashrc
      - run: exenv install --add v1.6.0-dev-a81a17b
      - run: exenv global v1.6.0-dev-a81a17b
      - run: exenv rehash
      # - run: git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.3.0
      # - run: echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.bashrc
      # - run: asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
      # - run: asdf install elixir ref:fba7e5c
      # - run: asdf install elixir ref:a81a17b-otp-20

      # Clone project
      - checkout

      # Install deps
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix deps.compile

      # Compile

      # TODO: Re-enable with Elixir v1.5.1
      # Elixir v1.5.0 has a bug where a warning can erroneously emitted for a
      # with with an else block even.
      - run: mix compile #--warnings-as-errors

      # Test
      - run: mix test --trace # TODO: Check coverage
